### ISSUE TITLE
Force AAC for surround audio by command

### ISSUE THREAD

**Issue by maverickjl07** [donmelton/other_video_transcoding#108]
Hi, I've been using video_transcoding for my library, and went to test **other_video_transcoding** and it's a LOT faster and quality seems the same to me. Thanks for making this all available. 

But on video_transcoding I can use a command to force AAC even on 5.1 (--audio-format all=aac together with --audio-width all=surround). On **other_video_transcoding** those commands don't exist, and I couldn't find a similar one.

**Comment by donmelton** [comment]
@maverickjl07 Thanks for using all of my tools!

And it's your lucky day, because I just implemented a `--aac-only` option for `other-transcode` last week which does that very thing. :) However, it does limit AAC surround to 5.1 channels for maximum playback compatibility.

I haven't released it yet and probably won't for a few more days. But you can download the version on GitHub and rename it to try it out.

Please let me know what you think.

**Comment by maverickjl07** [comment]
Thank you so much! That's exactly it. I did a quick test and it worked!

**Comment by donmelton** [comment]
@maverickjl07 Excellent! Thanks for the quick feedback.

I'll update this issue when it gets officially released.

**Comment by donmelton** [comment]
@maverickjl07 I released 0.9.0 today so `gem update other_video_transcoding` to get the final version. Thanks again!
