### ISSUE TITLE
Passthrough more DTS formats?

### ISSUE THREAD

**Issue by justinxfisher** [donmelton/other_video_transcoding#109]
I see `--pass-dts` can be used for DTS and DTS-ES, is there a way to passthrough DTS-HD tracks?

**Comment by donmelton** [comment]
@justinxfisher Yes, but it's not a single option that applies to all audio tracks. That's intentional because I actually want to discourage including lossless audio since that kind of misses the point of compression.

When you ask for full help via `other-transcode --help full`, you'll see this in the output:

```
    --main-audio TRACK[=WIDTH]
                    select main audio track by number (default: 1)
                      with optional width (default: surround)
                        (use `original` to disable transcoding)
    --add-audio TRACK|all|LANGUAGE|STRING[=WIDTH]
                    add single audio track by number
                      including main audio track
                    or all audio tracks
                      excluding main audio track
                    or audio tracks by language code
                      excluding main audio track
                      (in ISO 639-2 format, e.g.: `eng`)
                    or audio tracks with titles containing string
                      excluding main audio track
                      (comparison is case-insensitve)
                    with optional width (default: stereo)
                      (use `original` to disable transcoding)
```

As you can see, `original` can be used as a track "width" like `surround` and `stereo`. So, to simply copy the main audio track instead of transcoding it, add `--main-audio 1=original` to your command line. This will copy that track no matter what format it's in.

Does that answer your question?

**Comment by justinxfisher** [comment]
Hi,

Appreciate the quick and concise reply, and yes that completely answers the question.

I agree about it missing the point of compression. What I was attempting to test last night was a comparison between the DTS-HD track and the E-AC3 or AC3 to likely transition my encodes to one of those formats for that specific reason. I believe what I did wrong after seeing your reply was probably`—main-audio original` rather than including the track number.

Thanks again!
