### ISSUE TITLE
Transcoding file with space in name?

### ISSUE THREAD

**Issue by hawks28** [donmelton/other_video_transcoding#13]
Hello, I'm sure this is a very basic question. I have been able to transcode .mkv files where the filenames are one word titles. However, I am having trouble transcoding files that contain a space, or spaces, in the title. I know I can rename the files to remove the spaces, but I am hoping there might be a way to do this without renaming.

Here's the transcoding command I tried using: 

other-transcode --mp4 --burn-subtitle auto “/Volumes/Drobo/Video/_RippedDVDs/127 Hours.mkv”

And, here's the output from the terminal. As you'll see, the portion of the filename after "127" is not coming through the script. 

Office-iMac-2019:_RippedDVDs brucemenzel$ other-transcode --mp4 --burn-subtitle auto “/Volumes/Drobo/Video/_RippedDVDs/127 Hours.mkv”
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_videotoolbox" video encoder...
Scanning media...
/usr/local/bin/other-transcode: scanning media failed: “/Volumes/Drobo/Video/_RippedDVDs/127
Office-iMac-2019:_RippedDVDs brucemenzel$

Thanks in advance!

**Comment by donmelton** [comment]
@hawks28 The problem is not the spaces in your path name. I believe the problem is the particular quotation characters you're using to enclose that path name when you pass it as an argument on the command line.

It appears you're enclosing your path between `“` and `”` characters. These are sometimes known as "smart" or "curly" quotation characters. They're often used in word processors to make text more attractive, more like what you would see in a printed book. But the command line shell will not interpret them as quotation characters used to enclose a string.

You need to use the `"` charcacter to enclose both ends of your path name. It's the shifted character on the key just to the left of the of your "return" key.

Does that help?

**Comment by hawks28** [comment]
@donmelton Thanks, Don! That fixed the issue. I'm new to your transcoding tool and relatively new to using terminal commands so figured the issue was something basic. I had smart quotes turned on which was causing the issue. Thanks for the help and for developing/maintaining this great tool. It's been been very helpful in the short time I've been using it. Thanks!   


Bruce

**Comment by donmelton** [comment]
@hawks28 You are very welcome and thanks for using my tools!
