### ISSUE TITLE
AV1 encoding support in the future?

### ISSUE THREAD

**Issue by zenodotus280** [donmelton/other_video_transcoding#130]
I am converting my video library to h.265 now and am very happy with the results from my video card. I have since learned that there is a new and open codec being rolled out: AV1. It is about half the bitrate of h.265 for the same subjective quality (allegedly). A quick search through the code yielded only a single reference to it in what what appears to be some logic for decoding rather than encoding (related to QSV).

I didn't see any other issues discussing this topic either. Could you weigh in on the codec and how it fits in to the project being maintained here?

**Comment by ttyS0** [comment]
From what I understand, the issue is a lack of hardware accelerated encoding support for AV1 in consumer GPUs, regardless of vendor. I seem to remember reading that Google and Netflix are using custom ASICs for their AV1 encoding. To me, that implies it's a long ways off before AV1 finds its way into consumer "gaming" GPUs. 

I can't speak for Don, but I would guess that until there is hardware acceleration in consumer GPUs that `other-transcode` won't include it.

**Comment by donmelton** [comment]
@zenodotus280 There might be AV1 encoding support coming in the future but it's likely the Star Trek Future™. Mr. @ttyS0 is completely right, hardware-based AV1 encoding is not on anyone's consumer menu at the moment. Plus, the few AV1 software encoders out there are pathologically slow and will likely remain that way for some time.

BTW, the whole "half the bitrate of HEVC with the same quality" chatter is just the usual marketing crap about new technology. It's the just like when HEVC was supposed to have that same metric compared to H.264. And we know that wasn't true.

I'll leave this open for a bit in case anyone else wants to comment.

**Comment by zenodotus280** [comment]
Great - thanks again!

**Comment by donmelton** [comment]
@NathanJPlummer Thanks. Yeah, I'm keeping an eye on both AV1 and the new hardware encoders.

If you want to try out Intel's software encoder, take a look at my `av1-transcode.rb` script here:

https://github.com/donmelton/more-video-transcoding
