### ISSUE TITLE
No copy-audio option in other_video_transcoding

### ISSUE THREAD

**Issue by sweaver2** [donmelton/other_video_transcoding#136]
Hi Don,
I've been using your tool to transcode blu-ray rips, and I really just want to use it to transcode the video but keep the audio track intact. Video transcoding had a flag for --copy-audio, which does not seem present in Other video transcoding.

Is there a way to do full audio passthrough with other video transcoding?

Thank you.

**Comment by donmelton** [comment]
@sweaver2 Thanks for using my tools. Yes, there's a way to copy original audio tracks with `other-transcode`. But I don't make it obvious because I strongly discourage the practice. It simply goes against the goal of transcoding into a smaller, more portable format.

If you use `other-transcode --help full` and look in the "Audio options" section you'll see that there's an audio width that can be specified besides `surround` and `stereo`. Just use `original` for the width and the track will be copied. So, to copy instead of transcoding the main audio track you would add this option and argument to your command line:

```
--main-audio 1=original
```

If you only want to copy lossy DTS and DTS-ES audio then you would add then you would add this option to your command line:

```
--pass-dts
```

Does that answer your question?

**Comment by sweaver2** [comment]
Yes I believe it does, thank you for the info and the quick reply!

**Comment by donmelton** [comment]
@sweaver2 No problem and glad to help. I'll close this now then.
