### ISSUE TITLE
4K video comes out as 1080p

### ISSUE THREAD

**Issue by LwsBtlr** [donmelton/other_video_transcoding#147]
I have a 4K vide (3840x1608) that I ran through other-transcode and the result was a very good looking video at 1080p (1920x804). Is this expected behavior? Or do I have to force the target flag to 2160p?

**Comment by donmelton** [comment]
@LwsBtlr Yes, that's the expected behavior for AVC/H.264 output, which is the default. If you add the `--hevc` option to your command line then the output will not be automatically scaled to fit within a 1920- by 1080-pixel boundary.

I'm glad it looked good but keep in mind that if the 4K input also contained HDR color information then color mapping was likely wrong with that 8-bit AVC/H.264 output. It's best to use `--hevc --10-bit` when the input is HDR.

Does that answer your question?

**Comment by LwsBtlr** [comment]
Thanks for that, I did try —hevc after posting and just checked and sure enough, it preserved the 4K.
