### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by asheimo** [donmelton/other_video_transcoding#15]
Previously in `Transcode-Video` there was an option to prevent log files from being written `--no-log`. This was useful when handling multiple videos at one time so that you didn't have to go back and delete all the files. 

When first configuring `Other-Transcode` the log files are especially useful to get settings tweaked to your own preferences. Once you have dialed it in it would be nice to have the `--no-log` option back to make clean up a little simpler.

If I'm in the minority on this I will withdraw the request. Thanks.

**Comment by donmelton** [comment]
@asheimo My apologies for taking so long to respond. I've had a busy weekend.

Thank you for opening this issue, especially since it is so thoughtfully and politely worded. And that's true of all your other comments here on the project. I wanted to make sure you knew that, because I'm going to decline your enhancement request. Let me explain why...

I regret adding the `--no-log` option to my original `transcode-video` tool. Doing so made my job of supporting that software much more difficult. And many users of that option were disappointed when they realized, too late, that they had lost useful data.

Too often users would open issues after some kind of un-reproducible failure only for us both to discover they had no record of what they did because they had used `--no-log`.

And just as often after doing many transcodes with --no-log`, users would discover the `query-handbrake-log` tool and realize they couldn't go back and mine those logs for useful information.

So I will not add a `--no-log` option to `other-transcode`. Because I want to encourage users to keep their `.log` files. And if they still don't want to keep them, then `rm *.log` is a fine workaround.

I'll leave this issue open for awhile if you or others wish to comment.

**Comment by asheimo** [comment]
I am perfectly content with your explanation and withdraw the request without any hard feelings. Thanks.
