### ISSUE TITLE
other-transcode doesn't seem to be present?

### ISSUE THREAD

**Issue by scatteredbrain** [donmelton/other_video_transcoding#156]
Ok Don, get ready for the dumbest question ever:

I'm unable to get "other-transcode" working. I have installed the "older" transcoding files/bundles via homebrew and they seem to work(at least they launch and accept arguments, although I haven't done any *actual* transcoding...)

But I just tried to install your newer "other_video_transcoding" gem and it apparently installs fine:

`gem install other_video_transcoding
Fetching other_video_transcoding-0.10.0.gem
Successfully installed other_video_transcoding-0.10.0
Parsing documentation for other_video_transcoding-0.10.0
Installing ri documentation for other_video_transcoding-0.10.0
Done installing documentation for other_video_transcoding after 0 seconds
1 gem installed`

Trying to run it gives me: 

`other-transcode --help
-bash: other-transcode: command not found`

Now, I'm sure this is something simple like the wrong $PATH location or some such, but I tried some of the other suggestions and my path has /usr/local/bin like it's supposed to...and if I do the 

`ls -l /usr/local/bin/ffmpeg
lrwxr-xr-x  1 cen  admin  35 Nov  7  2020 /usr/local/bin/ffmpeg -> ../Cellar/ffmpeg/4.3.1_3/bin/ffmpeg`

it looks like it's in the right place(along with ffprobe and mkvpropedit).

So as many permutations of "'other-transcode' not working" or "'other-transcode' not found" don't reveal much, I'm checking with the boss-man himself.

Anyhoo, thanks in advance, I liked listening to you on your podcast a while back, hopefully you'll return to that world someday...

Cheers,
Chuck

**Comment by ttyS0** [comment]
Since `other-transcode` can run as a standalone script, it might be simpler to just drop it into `/usr/local/bin`.

For example, if you want the `v0.10.0` version:

```
curl -Lo /usr/local/bin/other-transcode https://github.com/donmelton/other_video_transcoding/raw/0.10.0/bin/other-transcode
chmod a+x /usr/local/bin/other-transcode

# If you want the ask-ffmpeg-log script too
curl -Lo https://github.com/donmelton/other_video_transcoding/raw/0.10.0/bin/ask-ffmpeg-log
chmod a+x /usr/local/bin/ask-ffmpeg-log
```

If you want the latest version (i.e. the one in the main branch), just replace `0.10.0` with `master`. 

```
curl -Lo /usr/local/bin/other-transcode https://github.com/donmelton/other_video_transcoding/raw/master/bin/other-transcode
chmod a+x /usr/local/bin/other-transcode

# If you want the ask-ffmpeg-log script too
curl -Lo https://github.com/donmelton/other_video_transcoding/raw/master/bin/ask-ffmpeg-log
chmod a+x /usr/local/bin/ask-ffmpeg-log
```

If you don't want to remember those commands, they can be wrapped up into an alias, shell function, or script. 

For example:

`alias update-other-transcode='curl -Lso /usr/local/bin/other-transcode https://github.com/donmelton/other_video_transcoding/raw/master/bin/other-transcode && chmod a+x /usr/local/bin/other-transcode'`

This is the approach I take, since Don's tools are about the only Ruby thing I use, so it allows me to avoid learning about how the `gem` system works. 😎

**Comment by donmelton** [comment]
@scatteredbrain Thanks for trying to use `other-transcode`. Yes, you have a `$PATH` problem but I don't know enough about your system configuration to diagnose it properly. Very likely it's due to the location for your Ruby Gems being missing from `$PATH`. Please realize that it's possible to successfully install Ruby Gems and still not be able to use them because of this.

Now, I can ask you for a load of diagnostic information about your system and I could _try_ to figure it out but, really, at this point you should probably follow @ttyS0 's excellent advice and install it manually.

How would you like to proceed?

**Comment by scatteredbrain** [comment]
Hey!  I'll take a crack at Sean's instructions.

Thanks!

**Comment by scatteredbrain** [comment]
And Done and works!

Thanks again both of you!

**Comment by donmelton** [comment]
@scatteredbrain Excellent! Again, many thanks to @ttyS0!

**Comment by loshlee** [comment]
Not dumbest ever! 
https://github.com/donmelton/other_video_transcoding/issues/132
