### ISSUE TITLE
Hardware Recommendation

### ISSUE THREAD

**Issue by briangoodman** [donmelton/other_video_transcoding#168]
I have been transcoding on my 2012 Mac mini using the defaults. I plan to retranscode all my MKVs (~1500) using 10-bit HEVC. The Wiki recommendation is Windows and an NVidia card, so I am looking for a cost-effective purchase recommendation for a small footprint computer. Any help would be appreciated as all my PC knowledge is 20 years out of date.

Thanks,

Brian

P.S. If this is the wrong forum for this question, please point me to the right one.

**Comment by donmelton** [comment]
@briangoodman I don't have a specific recommendation but you don't even a current Nvidia GPU to get great performance and quality. I have an Nvidia 2070 Super, which is two generations old, and it works very well.

I'll ask the HiveMind™ and see if they can recommend a particular system. Stay tuned...

**Comment by samhutchins** [comment]
IIRC there's some kind of gaming-focused NUC that includes an nvidia GPU. IIRC Gigabyte had some mini PCs as well.

General advice:
CPU: Core i5 or better, newer gens if possible (12th gen is current). AMD Ryzen 5 or better, newer gens if possible (5000 series is current, I believe)
GPU-wise: nvidia GTX 1660 or newer. Anything in the 20 and 30 series will do the trick. 30xx is newer. Lower numbers in the second pair (XX) are more entry level cards, but that won't affect transcoding at all.

**Comment by wintervaler** [comment]
@samhutchins is right about the gaming focused NUC, they do exist but are expensive and rare. 

Slightly less expensive and less rare, given your desire for a very small footprint, is if you can find a used (plenty on eBay off enterprise leases) Dell Optiplex Micro, HP ProDesk Mini or Elitedesk Mini, or Lenovo ThinkCentre Tiny — but one of the models that have a user-accessible PCIe slot, into which I think some people have been able to cram a single-slot Nvidia P400 or P600, which have the same encoder in them as some of Nvidia’s gaming-focused cards (but make sure it’s one with the Turing encoder, which is better quality and supports all of the features in `other-transcode`, and not the earlier Pascal encoder). Even a slightly larger Optiplex or ProDesk of the SFF rather than uSFF variety might suit your needs, you just need to find a low profile GPU so that it will fit in the chassis and still get you the Turing encoder. 

Honestly, though, if this is truly going to be purpose built for one single mighty transcode job, you could ditch the small form factor, go big for the sake of cost, and just sell the machine after you’re done and you’ll make some casual gamer very happy. You could easily put together a very cheap system with 8th or 9th gen Intel hardware and a GPU from EVGA’s b-stock sale every Wednesday, where there are 2060s regularly going for around $200 (disclaimer: I’m known around these parts for radical and sometimes ill-advised cost cutting. But these parts should suit the purpose just fine).  

Abstract ideas - sorry I can’t be more specific off the top of my head - but perhaps some directions to point you in!

**Comment by briangoodman** [comment]
I'd planned to let the transcoding job run uninterrupted for the Big Transcode™. Thinking about it now, heat would probably destroy the mini PC, so the idea of a full-sized PC to be resold makes sense. Once sold, I will need a small computer for ongoing additions to my library, so will be investigating the suggested small form factor PCs.

Thanks samhutchins, wintervaler and donmelton.

**Comment by donmelton** [comment]
@briangoodman You are very welcome! Would you like me to leave this open for awhile to see if anyone else chimes in?

**Comment by briangoodman** [comment]
Don, Please leave it open. Thanks

**Comment by klogg416** [comment]
@briangoodman I spent some time looking for a small formfactor with an appropriate GPU and basically only came up with this. https://www.hp.com/us-en/shop/pdp/hp-elitedesk-805-g8-desktop-mini-pc-customizable-2c5e4av-mb#techSpecs

There are many reasonably priced ones with Nvidia Quadro P6xx GPUs, but they are all from the Pascal generation that @wintervaler warned you off of. There is a T1000 GPU that replaced those Quadros, but it is a trick- Turning GPU with a Pascal encoder (TU117 GPU). See here, https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-application-note/#:~:text=NVENC%20can%20perform%20end%2Dto,residual%20coding%2C%20and%20entropy%20coding.

The HP linked at the top is a true Turing GPU. Second challenge with the mini PCs is that quite a few will let you add in a half height PCIe card, but I haven't seen any half height Nvidia GPUs in the Turning+ generation. I think @wintervaler's suggestion to go for a temporary solution is more realistic and should buy you time for the GPU tech to trickle down into business oriented mini PCs. The upside with using the GPU for transcoding and not gaming is that the power draw is very low, so you if you find a Dell SFF Opti plex or similar with a tiny PSU (350W or whatever), you can chuck a GPU in there without worry, just don't fire up 3D games. :-)

Good luck!

**Comment by klogg416** [comment]
One more link I should have pasted. Capabilities matrix so you can look up encode features by GPU. https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by BTMeeks** [comment]
> General advice: CPU: Core i5 or better, newer gens if possible (12th gen is current). 

I have a sandy bridge, 2500k. If I get a 1660 GPU, would I be OK, or do I need to update the CPU as well?

**Comment by donmelton** [comment]
@BTMeeks The 1660 is, more or less, a slightly slower 2060. So you're probably OK.

**Comment by samhutchins** [comment]
I have a 1660, it's the same encoder as the 20 series (and possibly 30, I forget what changed between 20xx and 30xx)

**Comment by NathanJPlummer** [comment]
@BTMeeks 

If you only care about video tasks, the a380 intel card linked below has special cores for video and AI, and supports newer codecs like AV1. It's a cheap, encoding powerhouse.

I get better video encoding results with this $130 card in my Linux server than I do with my RTX 3900 in my Windows machine.

The intel card is terrible for gaming, though.

https://www.newegg.com/asrock-arc-a380-a380-cli-6g/p/N82E16814930076?Description=arc%20a380&cm_re=arc_a380-_-14-930-076-_-Product

**Comment by klogg416** [comment]
Can you share the encode settings you are using for the a380 vs. RTX 3090?

**Comment by NathanJPlummer** [comment]
@klogg416 

Pretty simple settings.

For Nvidia:
-- HEVC --nvenc --10-bit --crop auto --nvidia-recommended

For Intel:

-- HEVC --qsv --10-bit --crop auto


If more knowledgeable people are curious and want me to doing a little bit of testing with some more exact settings, I don't mind reporting back.

Though the machines are wildly different besides just the GPU so it won't be a 1:1 comparison.

**Comment by briangoodman** [comment]
Don,

Unless there is demand to keep this issue open, I've gotten the answers I was seeking. Thanks everyone for your help.

Regards,

Brian
