### ISSUE TITLE
Crop values for particular passage

### ISSUE THREAD

**Issue by loshlee** [donmelton/other_video_transcoding#178]
The autocropping for other_video_transcoding is robust and usually works very well for me. Sometimes, however, transcoding crops using values that are undesired because a less important passage of the video is affecting them. Is there a way to specify a separate start and end time for detecting crop values, or do I just need to detect those on excerpts as a preliminary step in assigning the values? Thanks.

**Comment by donmelton** [comment]
@loshlee Unfortunately, the crop detection code always scans the full duration of the input media. Which means you need to use excerpts for detection of specific passages.

Just out of curiosity, is the automatic crop detection not being aggressive enough, i.e. not detecting a tight enough crop for you? Because if that's the case, then it's actually behaving the way I designed it. IOW, I intentionally wrote it in a way to try and prevent over-cropping, which is a problem that plagued older versions of HandBrake.

**Comment by loshlee** [comment]
OK, thanks! Yes, for me it tends to be overly inclusive, not cropping out as much as I'd like. So it's doing as you designed, which is probably best in most cases, so don't change a thing. I'm learning to use the crop detect and bitstream filters, so I can probably combine them to do what I'm asking and put it into an AppleScript to provide here if anyone could use it. Thanks again, and thanks again for other_video_transcoding!
