### ISSUE TITLE
Option to keep the original file's creation/modification date?

### ISSUE THREAD

**Issue by palla89** [donmelton/other_video_transcoding#185]
Hi! I don't know if I'm asking something stupid, but I wanted to transcode some twitch's vods and I was sorting them with the creation date that was set based on the streaming effective date. After transcoding, the newly created video doesn't keep these dates (and he's right!) but maybe an option to set the same properties of the original videos would be great!

What do you think? do you have any other idea on how I could accomplish this externally to this amazing toolset?

**Comment by donmelton** [comment]
@palla89 Thanks for using my tools! And solving this problem is best done using the mechanism that @ttyS0 (thanks, Sean!) just described and not a change to `other-transcode` itself because manipulating metadata---whether in the filesystem or not---is outside the scope of what the tool does.

Does that answer your question?

**Comment by palla89** [comment]
Thank you guys for your quick and helpful answers!! I'll go with touch, it's simple and exactly what I needed to, thank you both! ❤️
