### ISSUE TITLE
Issue with "scanning media failed"

### ISSUE THREAD

**Issue by kjkurtz** [donmelton/other_video_transcoding#21]
Hi there! Thanks so much for providing such quality tools to the community.

This is my first time with other_video_transcoding, having used video_transcoding for quite some time.

I'm running into an issue running this on a mac. Here is what I'm getting from the debug output:
```
Trying "h264_videotoolbox" video encoder...
Scanning media...
{

}
/usr/local/bin/other-transcode: scanning media failed: /Volumes/data/Movies/MOVIE_TITLE/
```
I'm running the command like this: `other-transcode /Volumes/data/Movies/MOVIE_TITLE/ --debug`

The movie is an image file from MakeMKV if it matters.

I'd appreciate any guidance. Thanks!

**Comment by donmelton** [comment]
@kjkurtz Thanks and thanks for using my tools! I'm sorry you're having this problem.

It looks like you're passing a directory and not an indivitual file to `other-transcode` as input. That won't work.

If you used MakeMKV, did you choose "Backup" instead of "Save selected titles" from the toolbar? If so, then output from MakeMKV will be a disc directory image which can't be passed to `other-transcode`.

You need to use MakeMKV to save an individual playlist as a standalone `.mkv` file from the disc you're ripping.

Does that make sense?

**Comment by kjkurtz** [comment]
Hi @donmelton,

Thanks for the quick reply! Yes, I was indeed using a directory as a result of a "Backup". Did the old `video_transcoding` toolset handle directories? I feel like that is how I did it there, but it has been awhile.

I re-ripped the movie to a `.mkv` and we appear to be smooth sailing now. 

As a result of the way this worked, is there no way to use `other-transcode` against a DVD directly, you have to use something like MakeMKV first?

Thanks so much!

**Comment by donmelton** [comment]
@kjkurtz My apologies for taking so long to reply. I've been AFK all day.

You are very welcome and I'm glad that recommendation worked for you.

The reason that `transcode-video` can use a disc image directory as input is because `HandBrakeCLI`, on which it is based, has that capability. The `ffmpeg` tool, on which `other-transcode` is based, does not.

However, while using a disc image directory as input sounds powerful, there are many limitations with transcoding that way. You are _much_ better off ripping your videos to single, standalone `.mkv` files.

I'll close this issue now, but feel free to continue commenting.
