### ISSUE TITLE
Will ffmpeg options pass through be implemented?

### ISSUE THREAD

**Issue by 69dragons** [donmelton/other_video_transcoding#23]
I like having the option of using Handbrake pass through flags in transcode-video. I am just wondering if something similar is in the works for other-transcode-video?

**Comment by donmelton** [comment]
@69dragons Thank you for your question.

I don't plan on allowing options to be passed through `other-transcode` to `ffmpeg`. This isn't practical because of the incredibly complicated command line syntax of `ffmpeg`. That syntax allows not only multiple inputs but multiple outputs. And options can be placed between those inputs and outputs making the argument order significant. This is further compounded by `ffmpeg`'s filter syntax and its argument order restrictions.

If you want that kind of control, you should really be using `ffmpeg` directly.

I hope that answers your question.

**Comment by 69dragons** [comment]
It does, so I will use the dry run to get the video opts and synthesize the audio and subtitle opts on the fly.

**Comment by donmelton** [comment]
@69dragons You are very welcome! And thanks for using my tools.

I'll close this now but feel free to comment here again.
