### ISSUE TITLE
TV Show Frame Rate

### ISSUE THREAD

**Issue by 69dragons** [donmelton/other_video_transcoding#25]
Why does other-transcode-video change the frame rate from 29.97 fps to 24.97 fps?

Wouldn't it be better for TV shows the be kept in their native frame rate?

**Comment by donmelton** [comment]
@69dragons Thank you for your question. I assume you're referring to TV episodes ripped from DVDs rather than Blu-ray Discs?

The `other-transcode` tool behaves much like my older `transcode-video` tool. That is, for any video input with a rate of 29.97 FPS or video that's already interlaced, a deinterlace filter is automatically applied. Additionally, if that input is also in MPEG-2 format (like all DVD rips) then the frame rate is changed to 23.976 FPS.

If these changes are not made, the video usually has motion artifacts like combing. Additionally, the video is often lower quality because unneeded frames are being transcoded.

You can disable this automatic behavior using the `--no-filters` option but I would strongly advise against that.

I hope this answers your question.

**Comment by 69dragons** [comment]
Yes, I guess it never paid attention to that behavior in transcode-video. And your assumption is correct I am working with DVD Rips.

Thanks for being right there for support.

**Comment by donmelton** [comment]
@69dragons No problem! Did you have any other questions about this behavior?
