### ISSUE TITLE
Quality difference between older Nvidia cards (GTX 10xx) and newer (RTX 20xx)?

### ISSUE THREAD

**Issue by lambdan** [donmelton/other_video_transcoding#28]
I'm on a 1080 TI and it's a great card for gaming and I'm very impressed with how fast it can encode HEVC 10-bit using other-transcode without me noticing any obvious quality drop.

But I'm curious if switching to a newer RTX card would result in even better quality at the same bitrate?

I know this is a marketing page, but on this page: https://www.nvidia.com/en-us/geforce/news/geforce-rtx-streaming/ they have this paragraph:

> GeForce RTX GPUs are up to 15% more efficient (i.e. require 15% less bitrate at the same quality level) than previous-generation Pascal GPUs when streaming in H.264, thanks to architectural improvements to the dedicated hardware encoder, NVENC.

They're talking about H264 there, but maybe it applies to HEVC too?

I'm curious if any of you have tried both generations of cards and noticed any difference?

**Comment by donmelton** [comment]
@lambdan This is a great question! And, yes, myself and my collaborators spent quite a bit of time last year testing this very difference.

Just so you know, I also have an Nvidia GeForce GTX 1080 Ti card. Here's what we found...

* The older GTX 10xx cards are usually faster than the newer RTX 20xx cards. Go figure. I suspect this is because the older cards 1) have more encoding cores and 2) Nvidia optimized the newer cards for the default streaming-style ratecontrol system which I'm not using in`other-transcode`.

* The newer RTX 20xx cards allow the use of temporal AQ (adaptive quantization) in HEVC output. Enabling that with the `--nvenc-temporal-aq` option will improve HEVC quality slightly but, honestly, this is really only noticeable for some edge cases. There's also a very small performance penalty for using it. However, I do enable temporal AQ by default for H.264 output where it does seem to make more of a difference in quality because both the GTX 10xx and RTX 20xx cards are capable of using it.

Does that answer your question?

**Comment by lambdan** [comment]
Fascinating. But it also makes sense that the newer cards are more optimized for the thing NVENC is likely most used for: streaming.
So yeah, that answers my question.

I guess I'll just keep other-transcoding with my 1080 TI and don't feel bad about it. Maybe the 3000-series card will have greater differences and I could get that instead.

**Comment by donmelton** [comment]
@lambdan Yeah, the whole team here is very curious as to the performance and quality output of the new "Ampere" cards set to debut later this year. :)

OK, I'll close this now but feel free to comment more here or keep asking these great questions.
