### ISSUE TITLE
GPU vs software 10-bit HEVC encodes?

### ISSUE THREAD

**Issue by Thor263** [donmelton/other_video_transcoding#31]
Since I've recently started playing with `other-transcode`, I've been curious about something. I have a 2018 Mac mini and have been testing software 10-bit HEVC encodes due to the limitations of VideoToolbox and 8-bit input. With my Blu-ray sources I tend to get around 15 FPS, which usually means encoding time is close to double the real running time of a movie. I know I could utilize Boot Camp to take advantage of the Mac mini's  Intel 630 (fairly impressive results from one the responses in Issue #29) and I do have other hardware in which I could use a Windows and an Nvidia card. My question is if there is a noticeable difference in quality between a 10-bit HEVC software encode vs a GPU encode? I'd be willing to invest some time or money if there is.

**Comment by ttyS0** [comment]
I think the general consensus is Nvidia driven 10-bit HEVC is the "gold standard" when it comes to hardware accelerated transcoding. While software may get a little bit better quality, it's _really_ hard to justify losing an order of magnitude of FPS performance for a small gain. I recently retranscoded my BluRay rips, switching them to 10-bit HEVC via Nvidia transcoding, and am very happy with the results. They look a little better than the previous H.264 encodings, and take up a little less space. 

;tldr Since you have an Nvidia card (assuming it's Pascal or better), I think the general advice will be to use that for all your 10-bit HEVC encodes. 😄

**Comment by khaosx** [comment]
@ttyS0 is not exaggerating when he says order of magnitude. We've seen several examples of the quality improvements in 10-bit HEVC in our test suite where scenes we've written off as "as good as it gets" aren't even noticeable. If you have the resources to go to a Windows/nVidia solution for your transcoding, you're going to be impressed by both speed and quality.

**Comment by donmelton** [comment]
@Thor263 I would agree with the assessments by @ttyS0 and @khaosx (Thanks, guys!) and advise you also to do whatever you can to leverage that Nvidia card. Trust me, it's not worth your time to wait around for software-based encoders.

**Comment by Thor263** [comment]
Thanks for the responses everyone. It was a little ambiguous as to whether I had an Nvidia card or not...I currently don't, but I'm going to be picking one up!

**Comment by donmelton** [comment]
@Thor263 Let us know how that goes then!

I'll close this now but feel free to comment here or elsewhere.

**Comment by mo-han** [comment]
> it's not worth your time to wait around for software-based encoders.

why?
when at a same bitrate, x265 output quailty beats any popular hardware hevc encoders, such as qsv, nvenc, etc.

hardware encoders are way faster than cpu, yes, but they tradeoff quality/size ratio for speed.
so they are popular in the field of livestreaming, as the creators only need to up-stream their frames to the service platform, with fast speed ,low load, and enough good quality, the bitrate is not very important, since nowadays network are enough fast and cheap.
the livestreaming platform will re-encode their uploaded data anyway, with much more powerful computing clusters, to generate the down-stream for the audiance, and it's generated with slower encoder to achieve lower bitrate to save the bandwidth cost.
similar for those content providing users, although they don't upload live video streaming, they upload video files, after finishing the cutting and editing, during which they don't care much about the quality/size ratio -- quality is important, but the size could be oversized, it's fine since the platforms like youtube will re-encode the uploaded videos with more powerful and slower encoders to achieve high quality/size ratio, to save their bandwidth cost.

but when it coms to home/personal collections, the story is different.
there is no a big company using their powerful computing clusters to re-encode our video files, we do that work for ourselves.
we care about the final quality/size ratio, very much.
the speed is very import as well, but if high speed is bound to low quality/size ratio, then i'd rather take more time to use x265 to achieve good quality and small size, in cost of time.
since these beloved collections will be there for long time, doing a good one-time encoding job is worth.
on the other hand, if the collection is not that favorite, and might be deleted soon afterwards, i'll use hardware encoders to treat them, you know, not worthy.
