### ISSUE TITLE
Questions about your 'main system' playback setup.

### ISSUE THREAD

**Issue by weaverm** [donmelton/other_video_transcoding#33]
I've used video_transcoding for quite a while now (& really like it!) and I've played with other_video_transcoding. I've transcoded all my movies and most of my TV shows. Generally, I understand the goal of turning the somewhat unwieldy MKV rips into smaller & more portable files that still look great. I've been producing .m4v files which I then load into my iTunes library. I plop those files on my iPad when I travel or access them via an AppleTV when I'm on the couch.

When I started down this rabbit hole a couple years ago, I heard Don on a podcast talking about transcoding (with Rene Ritchie I think). I seem to recall he mentioned he keeps all his rips since making the rip takes a lot of work, the compression format of today isn't necessarily the compression format of tomorrow, and hard drive space is cheap(-ish). So, I've kept all my rips.

A couple weeks ago I got a Raspberry Pi 4 and put Plex on it as an experiment. It works. And now it has me wondering, what does the community here do for their main system? I'm assuming most folks here have a home theater somewhere in their abode and this is their best place for watching movies. Are most people using Plex? And are you watching the transcoded files, either 8-bit H.264 or 10-bit H.265?

My main system is a 4k LG OLED TV with an AppleTV 4k on ethernet. My Raspberry Pi 4 Plex server seemed to work just fine with 'raw' 1080p Blu-ray & 4k UHD rips (made with MakeMKV). I'm sure it wouldn't work so well if it had to transcode that stuff on the fly, but to my 'main system' it doesn't have to. Assuming storage isn't an issue, is watching the 'raw' rips on my 'main system' the best thing I can do? And then is using my lovingly transcoded files in almost all other instances the best thing? What do y'all do?

**Comment by asheimo** [comment]
Me personally I currently use a MacMini (late 2014) as my Plex server. But I also built a couple of my friends plex servers from old boxes they had. In all cases I stuck with h264 for all my transcodes for compatibility of playback, but I'm currently re-transcoding to hevc since all my playback screens can handle it (iDevice, SamsungTV 4k, Playstation4, PC w/4k HDR monitor using the Plex app). Since you're using other-transcode the default when converting to hevc is 10bit and it's worth it. The banding that fixes is worth it.Some of us also started using Plex for our music and the PlexAmp app is really pretty neat.

**Comment by klogg416** [comment]
@weaverm, my set up is very similar to yours. I have most of my original rips on a NAS, and stream them to my main home theatre using Kodi on a reflashed AndroidTV box. All the other screens and devices are running Plex and get the transcoded files, which are 10bit HEVC files. The transcoded files are good enough for the main system too, but since the raw rips are stored on a NAS, seems silly to ignore them on the best screen...

**Comment by ttyS0** [comment]
@weaverm I have a bit of an over engineered setup, but it works well for me.

 I'm running Plex on a [home lab Kubernetes cluster](https://github.com/ttyS0/kubernetes/blob/master/plex/plex-server.yaml). I restrict Plex to Intel NUC nodes so I can take advantage of hardware transcoding via QSV (i.e. `/dev/dri`). I'm using [Ceph](https://ceph.io) for storage. For playback, I'm using an AppleTV with a 60" 1080p TV.

I keep my rips in AWS S3, and since I don't have an Nvidia card I use an [AWS GPU EC2 instance](https://github.com/ttyS0/terraform/blob/master/AWS/transcode.tf) and a [Docker container of other-transcoding](https://github.com/ttyS0/docker-transcode-nvidia) to do 10bit HEVC transcoding. The source rip stays in S3 (Deep Archive StorageClass), and the transcode is pulled down to the local Plex system.

**Comment by weaverm** [comment]
@klogg416 So you use Kodi to serve rips to your main home theater and then Plex for transcoded files to everything else? I discovered today that [Plex supports multiple versions](https://support.plex.tv/articles/200381043-multi-version-movies/) of the same movie. In my simple testing, the Plex client on AppleTV lets me pick which version I want to watch.

@ttyS0 Like you, I don't have an Nvidia card, since I have an iMac. It hasn't occurred to me to use an AWS GPU instance for transcoding. You look like you're using a gd4n.xlarge, which looks like it has a Turing based GPU and seems to cost around 50¢/hour. I see the [S3 Glacier Deep Archive](https://aws.amazon.com/s3/pricing/) storage level is $0.00099/GB/mo in most regions, which isn't very much; around $1/TB/month. Moving roughly 30GB Blu-ray rips to S3 might be tedious but I guess it is a 1-time pain per movie.

**Comment by ttyS0** [comment]
@weaverm Using spot instances that can get down into the 0.18-0.25 cents per hour territory. Now, the bad news:

* uploads can take a while

* once you convert a file to Deep Archive it has to be restored in order to copy it to an EC2 instance for transcoding, and there are costs associated with that

* there is cost associated with downloading the transcoded files

All in all, I think it’s worth it. 😎

**Comment by klogg416** [comment]
@weaverm You've got it. You might be right about Plex supporting multiple versions, I just kind of hate Plex's UI and don't want it as my primary interface. It serves a purpose and does a good enough job, but it isn't my favourite. So I roll with Kodi when I can.

**Comment by samhutchins** [comment]
I have Plex running on a DS418play. It hosts films, TV, music, and photos.

I have a Roku Premier (UK one)

Most of my stuff is h264+ac3+aac, more recent stuff is hevc+ac3. 

I transcode for 2 main reasons: space on the synology, and network congestion. I live in a flat where I can't run ethernet, so most of my stuff is on Wifi, including the Roku.

**Comment by weaverm** [comment]
As I get a little deeper into Plex the intricacies of playing video files have become more apparent. Plex has [Direct Play, Direct Stream](https://support.plex.tv/articles/200250387-streaming-media-direct-play-and-direct-stream/) and transcode ways to get a movie from the server to your screen. What happens and when is dependent on lots of variables, not the least of which is the client's playback capabilities. One upside of watching transcoded stuff on one's 'main system' is the transcoded output can be tailored to whatever will work the best for that system.

**Comment by samhutchins** [comment]
Yeah, I have a "zero transcode" policy for Plex within my household, and transcoding to a standard format that I know plays on all my devices is what allows that.

**Comment by weaverm** [comment]
I've settled into a little-bit-weird hybrid setup. I have a few 4k movies (rips from MakeMKV) that I serve to my AppleTV via Plex on Raspberry Pi (either via Direct Play or Direct Stream). Everything else continues to live in my iTunes as h264 transcodes. I don't love iTunes or Plex, but since the 4K HDR transcode situation is what it is, this lets me watch my 4k movies on my 4k TV well enough. Moving all onto Plex seems like a lot of trouble for not a lot of gain. My time is likely better spent doing 10-bit h265 transcodes for the things that'll benefit from that. But maybe I'm missing something?

**Comment by donmelton** [comment]
@weaverm I just realized we never answered your final question here. My apologies. But if that's working for you, stick with it.

I'll close this for now.
