### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by platonium** [donmelton/other_video_transcoding#37]
Hi, Don and the Transcode Crew, it's been a while. Love the new tool and have moved to it exclusively. Did run into an odd issue with a transcode recently. The rest of the video looks great, but there's about a 2:40 segment that seems to sutter - like being under a strobe light. The source mkv looks fine for that same period.

The source is a DVD. Fumbling around, I did the first run using OT plain and a second run with --x265 (just to see what would happen). Both times, it seems pretty much the same and only applies to those 2:40 minutes. The movie is the Secret Garden 1993 so there's not much in the way of fx either. 

Thanks, and hope everyone is safe and well this long weekend.

**Comment by klogg416** [comment]
Hi @platoniun,

What are you using for playback? We have seen that kind of behaviour on slightly underpowered devices deciding h265 streams in software. The AppleTV generation before the 4K model is an example of this, works great 98% of the time, and then does a weird time compression / strobe / massively dropped frames dance for a few seconds when a scene is too complex. 


accounts@klaynation.com

**Comment by platonium** [comment]
Thanks, it’s happening in the exact same section of video (with both transcodes) for both a TCL TV and on the Acer Laptop used for the encoding. The scenes before and after as well as films I would think are more demanding like a BD transcode of Terminator Dark Fate play smoothly.

Sent from my iPhone

On May 24, 2020, at 5:11 AM, Kyle <notifications@github.com> wrote:

﻿

Hi @platoniun,

What are you using for playback? We have seen that kind of behaviour on slightly underpowered devices deciding h265 streams in software. The AppleTV generation before the 4K model is an example of this, works great 98% of the time, and then does a weird time compression / strobe / massively dropped frames dance for a few seconds when a scene is too complex.


accounts@klaynation.com

**Comment by klogg416** [comment]
If the issue was the player then I would expect the problem to be in the same spot on both encoders, but given you are experiencing it on two devices then likely you are getting tripped up by something else. Have you confirmed the source file plays correctly? Checked the logs for errors?

**Comment by platonium** [comment]
Thanks, when I look at the log (which I don't really understand). Ctrl-F 
"error" returns only this:

ffmpeg -loglevel error -stats -i (etc, etc)

Is there something specific for which I should be looking?

**Comment by klogg416** [comment]
Can you paste the log in [here](https://pastebin.com/) and reply with the link?

**Comment by platonium** [comment]
Thank you so much: https://pastebin.com/CyamCsYD.

**Comment by klogg416** [comment]
No errors in there that jump out to me, normally there is a giant spew of garbage at the end if there is a problem during the transcode. 

Can you confirm that watching the input file doesn’t show the same problem?

Beyond that, I’m afraid I need to hand off to @donmelton for new ideas

**Comment by platonium** [comment]
Thanks for checking that out. The source seems fine - at least by my eye. No artifacts before or after the affected sequence.

Sent from my iPhone

On May 25, 2020, at 11:46 AM, Kyle <notifications@github.com> wrote:

﻿

No errors in there that jump out to me, normally there is a giant spew of garbage at the end if there is a problem during the transcode.

Can you confirm that watching the input file doesn’t show the same problem?

Beyond that, I’m afraid I need to hand off to @donmelton<https://github.com/donmelton> for new ideas

**Comment by donmelton** [comment]
@platonium Sorry I took so long to respond but @klogg416 was doing such an excellent job with his diagnosis that I didn't think intervention was necessary.

But I must say that I'm at a loss because there's nothing in the `.log` file that you very nicely provided which would indicate a problem. :(

As @klogg416 mentioned, when this happens it's sometimes due to a problem within the source. However, weirdly that does not mean the source has playback problems itself. Often it is a subtle issue with `ffmpeg` or other encoding tools reading timing information within the video stream.

So, as an experiment I want you to try two more transcodes of this movie with slightly different options.

For the first experimental transcode, try adding `--no-filters` to your command line. This will disable automatic deinterlacing and forcing a frame rate of `23.976` FPS.

For the second, try adding `--deinterlace` to your command line. This will only disable forcing the frame rate.

If both of these two transcodes still exhibit the same problem then my only suggestion would be to re-rip the movie.

**Comment by klogg416** [comment]
Thanks @donmelton, appreciate the next steps.

**Comment by platonium** [comment]
Thanks to both of you for your help and assistance. The no filter option 
worked so it must be some kind of weird defect in the source. Very much 
appreciate all the guidance as always.
