### ISSUE TITLE
Ruby issue

### ISSUE THREAD

**Issue by robbieroof** [donmelton/other_video_transcoding#57]
Hi Don,
I get the following error when I try to install other_video_transcoding...

You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

Any thoughts on how to repair??

Thanks.

**Comment by donmelton** [comment]
@robbieroof You could try `sudo gem install other_video_transcoding` as suggested in the README document.

However, it might be best to install Homebrew first and then install your own version of Ruby. That's what I do because that won't require administrator privileges just to install a Gem. You can install all of the dependencies easily with Homebrew as well. You can find out more about Homebrew here:

http://brew.sh/

Unless of course the problem is that you already have Homebrew and a custom Ruby installed and you're getting that error?

**Comment by donmelton** [comment]
My thanks to @Muhammad-cp for his answer!
