### ISSUE TITLE
HDR Passthrough?

### ISSUE THREAD

**Issue by RusselProuse34** [donmelton/other_video_transcoding#65]
Hi folks,

I've been using other-transcode for a while to transcode some 1080p Blu-Rays that I have into HEVC based MP4s for playback on various iOS devices and my Apple TV. I also recently purchased an LG OLED TV and have started collecting some 4K Blu-Rays as well. I'm still mostly a beginner when it comes to tools like ffmpeg (which is why I like your tools so much, Don!), but from what I've been able to find through searching online, most people say thta transcoding files using ffmpeg and retaining HDR data still appears to be a problem in some respects. However, others are saying that it's possible to include HDR data in a transcode, at least with software encoding (see here: [https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/](url)). And as of a few days ago, it appears (again, I'm still a beginner so I apologize if this is incorrect) that a bug fix is being implemented for hardware based encoders like nvenc - see here: [https://patchwork.ffmpeg.org/project/ffmpeg/patch/A384B59E-32E4-459A-AF0C-47BC551E007F@me.com/](url).

Anyway, this is a long winded way of getting to my question. Is is possible to retain HDR data on a transcode using hardware encoders like nvenc or qsv, through your tools or otherwise? And if not yet, does the bug fix I referenced above mean that that support could be coming soon to other-transcode and ffmpeg as a whole?

Cheers.

**Comment by rhapsodians** [comment]
Hi @RusselProuse34,

Assuming you're using something like Plex as the media server, there is currently only one way to guarantee 4K (with HDR) on your OLED. First thing, I assume you have an Apple TV 4K (as opposed to the original 4th gen - if it's not a 4K, there's no HDR support).

So the steps to get 4K/HDR playback on the OLED are as follows:

1. Use MakeMKV (latest version) to rip the 4K disk -> MKV. Your physical BR drive also needs to be 4K-savy and may need to be patched to allow any software to read commercially purchased 4K discs.
2. Once you have a Movie.mkv, don't do anything to it - keep it in its raw format and add it to Plex. It may be 50GB but that's the trade-off at the moment. 
3. Don't transcode it - it will almost always cause colours to be washed out and look awful. There are a few experimental techniques for HDR10 only but there's nothing foolproof yet due to the nature of HDR10, HDR10+ and Dolby Vision.
4. When you configure your LG, you need to make sure your entire flow is HDR-compatible:  HDMI cables have to be 4K/HDR HDMI 2.0/2.1 certified ... if they're not, it just won't have the bandwidth to carry the HDR stream. I'd also recommend using a wired, Ethernet connection as opposed to Wifi as you can easily hit 50-60 Mbit/sec being streamed with 4K-HDR raw. Unless you know you're wifi is solid, then you'll start to buffer and stutter.
5. Because most 4k/HDR disc purchases also come with a regular 1080p Blu-ray, my advice is to transcode the 1080p version so you have it.
6. To keep things clean in Plex, it's best to separate 4K and 1080p content so create a separate 4K library for 4K stuff (e.g. "4K Movies", "4K TV" etc. 

So at the moment, nobody has solved the 4K/HDR transcoding conundrum so the above approach is the best for now. When it is solved, no doubt you'll hear a lot of chatter here because many of us have been looking for solutions (and experimenting too).

One final thing - I'd recommend switching from MP4 to MKV if you can ... one of the big advantages is that subtitles (PGS streams) can be included/embedded in the mkv file. Then, if you use Plex alongside an AppleTV 4K, a Fire TV 4K or the new Nvidia Shields, you can use them with no server-side on-the-fly transcoding penalty - they will Direct Play and just work.

**Comment by donmelton** [comment]
@rhapsodians Thanks, Joe! These are great recommendations.

**Comment by RusselProuse34** [comment]
Thank you Joe for the excellent information. I do indeed have an Apple TV 4K with a Plex server so this response was very helpful.

One more question - it was my understanding that MKV containers don’t play nicely with Apple devices, and that playing an MKV source file through Plex on my Apple TV would automatically trigger a transcode from the server, regardless if it’s encoded as h.264 or HEVC. Is that not the case?

**Comment by asheimo** [comment]
@RusselProuse34 we figured out how to add the HDR info after `other-transcode` post-processing. The submitter of the patch specifically calls out that it only adds the info to the container, we do the same.

I have a little GUI that I use to copy the info that you can find here: https://github.com/asheimo/HDRCopy and I think there is a bash script to do the same thing not sure which of us has that.

**Comment by donmelton** [comment]
@asheimo Thanks, Andy!

**Comment by khaosx** [comment]
@RusselProuse34 - I have an AppleTV 4k, and can direct play all of my 4k rips with HDR metadata. The mkv container is a godsend, and I highly recommend it It's future proof, at least as far as we can see the future, and you should have no problems with any file in it.

Here's the HDR copy script, in Powershell. You'll need mediainfo. This is a quick and dirty that I threw together, but feel free to expand on it, or ask any questions you might have.

```
# hdr-copy-metadata.ps1
# 
# Version: 1.0
# Reads HDR metadata from source file and applies it to a transcoded output file.

 param(
  [Parameter(Mandatory)]
  [string]$fsource,
  [Parameter(Mandatory)]
  [string]$fdest
)

# Pre-defined RGB & WP values for BT.2020
$BT2020_xW = 0.3127
$BT2020_yW = 0.3290
$BT2020_xR = 0.708
$BT2020_yR = 0.292
$BT2020_xG = 0.17
$BT2020_yG = 0.797
$BT2020_xB = 0.131
$BT2020_yB = 0.046

# Pre-defined RGB & WP values for P3-D65
$P3D65_xW = 0.3127
$P3D65_yW = 0.3290
$P3D65_xR = 0.680
$P3D65_yR = 0.320
$P3D65_xG = 0.265
$P3D65_yG = 0.690
$P3D65_xB = 0.150
$P3D65_yB = 0.060

# Extract values from source video
$colourSpace = mediainfo --Inform="Video;%MasteringDisplay_ColorPrimaries%" "$fSource"
$luminance = mediainfo --Inform="Video;%MasteringDisplay_Luminance%" "$fSource"
$maxCLL =  mediainfo --Inform="Video;%MaxCLL%" "$fSource"
$maxFALL = mediainfo --Inform="Video;%MaxFALL%" "$fSource"
if ( $maxCLL -eq "" ) {
  $maxCLL = "0 cd/m2"
}
if ( $maxFALL -eq "" ) {
  $maxFALL = "0 cd/m2"
}  

# Print results from MediaInfo
write-host "Colour Space: $colourSpace"
write-host "Luminance: $luminance"
write-host "MaxCLL: $maxCLL"
write-host "MaxFALL: $maxFALL"

# Extract max and min lumanances
$minLuminance = $luminance.split( )[1]
$maxLuminance = $luminance.split( )[4]

# Extract MaxCLL
$maxCLL_noUnit = $maxCLL.split( )[0]

# Extract MaxFALL
$maxFALL_noUnit = $maxFALL.split( )[0]

# Print extracted values
write-host "Minimum luminance: $minLuminance"
write-host "Maximum luminance: $maxLuminance"
write-host "MaxCLL: $maxCLL_noUnit"
write-host "MaxFALL: $maxFALL_noUnit"

# Edit second input based on values extracted from MediaInfo
switch ($colourSpace) {
  "BT.2020" {
    mkvpropedit "$fDest" --edit track:v1 --set chromaticity-coordinates-red-x="$BT2020_xR" `
	--set chromaticity-coordinates-red-y=$BT2020_yR   `
	--set chromaticity-coordinates-green-x=$BT2020_xG `
	--set chromaticity-coordinates-green-y=$BT2020_yG `
	--set chromaticity-coordinates-blue-x=$BT2020_xB  `
	--set chromaticity-coordinates-blue-y=$BT2020_yB  `
	--set white-coordinates-x=$BT2020_xW              `
	--set white-coordinates-y=$BT2020_yW              `
	--set max-luminance=$maxLuminance                 `
	--set min-luminance=$minLuminance                 `
	--set max-content-light=$maxCLL_noUnit            `
	--set max-frame-light=$maxFALL_noUnit
  }
  "Display P3" {
    mkvpropedit "$fDest" --edit track:v1 --set chromaticity-coordinates-red-x="$P3D65_xR" `
    --set chromaticity-coordinates-red-y=$P3D65_yR     `
	--set chromaticity-coordinates-green-x=$P3D65_xG   `
	--set chromaticity-coordinates-green-y=$P3D65_yG   `
	--set chromaticity-coordinates-blue-x=$P3D65_xB    `
	--set chromaticity-coordinates-blue-y=$P3D65_yB    `
	--set white-coordinates-x=$P3D65_xW                `
	--set white-coordinates-y=$P3D65_yW                `
	--set max-luminance=$maxLuminance                  `
	--set min-luminance=$minLuminance                  `
	--set max-content-light=$maxCLL_noUnit             `
	--set max-frame-light=$maxFALL_noUnit
  }
  default { write-warning "Unknown Colourspace" }
}  ```

**Comment by donmelton** [comment]
@khaosx Thanks, Kris!

**Comment by rhapsodians** [comment]
> Thank you Joe for the excellent information. I do indeed have an Apple TV 4K with a Plex server so this response was very helpful.
> 
> One more question - it was my understanding that MKV containers don’t play nicely with Apple devices, and that playing an MKV source file through Plex on my Apple TV would automatically trigger a transcode from the server, regardless if it’s encoded as h.264 or HEVC. Is that not the case?

@RusselProuse34 If you have an MKV and try to play it using iTunes, then you're right, it's not supported. But MKV is a container and the audio/video/subtitle streams contains within are the key. There are so options for Apple TV: Plex Client, Infuse Pro, even VLC all play MKV natively and without issue. Specifically, AVC/HEVC video, AC-3, EAC-3, AAC audio and PGS subs are all supported natively. Serverside transcoding only takes place when the h/w running the client software can't natively decode/play either the video, audio or subtitle streams. 

In this case, the server 'transcodes' it on-the-fly to a format the client can play. So when you run the Plex client on an Apple TV 4K, Fire TV (and FTV 4K), Shield etc., with the above formats within MKV, it's plays Direct Play and perfectly. The Shields also natively decode DTS/DTS-HD MA because they licensed the codecs.

So the advice is to move to MKV if you can, use Don's tools to generate AVC/HEVC with the audio/subs you need - and then let your Plex Server and client on the ATV4K do the rest. You should be able to Direct Play (or Stream) absolutely everything in this scenario.

**Comment by khaosx** [comment]
@RusselProuse34 We're all pretty geeky around here so this advice will go against the grain, but one lesson we keep coming back to, whether it's audio files, movies, or just about anything - Don't try to be smarter than Plex. It just makes Plex do dumb things. I keep trying to outthink it, and it just ends in heartbreak every time! :)

**Comment by donmelton** [comment]
@khaosx Truth!

**Comment by martinpickett** [comment]
I am a bit late to this, but here is the Bash equivalent to @khaosx Power Shell script.

https://gist.github.com/martinpickett/1bbb1675c86eef67fe42409ff7430f73

This script is easy to run, just pass it the source (Blu-Ray rip) first and the transcode second and it will copy the HDR10 metadata from the source to the transcode.

`HDRCopy.sh source.mkv transcode.mkv`

To run this script you will need MediaInfo installed as a command line utility.

**Comment by Thor263** [comment]
Wow, these HDR scripts are great...thanks for sharing everyone! I'll have to try these along w/ my fairly new Nvidia card on some of the 4K movies that I have.

**Comment by donmelton** [comment]
@martinpickett Thanks, Martin! I think the HiveMind™ has given @RusselProuse34 "total coverage" on his original question. :)

So, has this been resolved now?

**Comment by RusselProuse34** [comment]
Absolutely Don. Thanks very much everyone for the great info. HDR still seems like a tricky puzzle but it’s great to know that there’s already some good tools out there that can help.

**Comment by donmelton** [comment]
@RusselProuse34 No problem! Good tools and and a very responsive HiveMind™. :)

**Comment by CaptSonic** [comment]
I have taken the script form RusselProuse34 and it works as desired. Unfortunately I get the "Unknown Colourspace" error with this file for example.

Anyone an idea why?

> Video #1
> ID                                       : 1
> Format                                   : HEVC
> Format/Info                              : High Efficiency Video Coding
> Format-Profil                            : Main 10@L5.1@High
> HDR format                               : SMPTE ST 2086, HDR10 compatible
> Codec-ID                                 : hev1
> Codec-ID/Info                            : High Efficiency Video Coding
> Dauer                                    : 2 h 14 min
> Bitrate                                  : 44,3 Mb/s
> Breite                                   : 3 840 Pixel
> Höhe                                     : 2 160 Pixel
> Bildseitenverhältnis                     : 16:9
> Modus der Bildwiederholungsrate          : konstant
> Bildwiederholungsrate                    : 23,976 (24000/1001) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0 (Type 2)
> Bit depth                                : 10 bits
> Bits/(Pixel*Frame)                       : 0.223
> Stream-Größe                             : 41,7 GiB (85%)
> Default                                  : Nein
> Kodierungs-Datum                         : UTC 2019-03-06 12:44:36
> Tagging-Datum                            : UTC 2019-03-06 12:44:36
> Color range                              : Limited
> Color primaries                          : BT.2020
> Transfer characteristics                 : PQ
> Matrix coefficients                      : BT.2020 non-constant
> Mastering display color primaries        : Display P3
> Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
> Codec configuration box                  : hvcC
> 
> Video #2
> ID                                       : 2
> Format                                   : HEVC
> Format/Info                              : High Efficiency Video Coding
> Format-Profil                            : Main 10@L5.1@High
> HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
> Codec-ID                                 : dvhe
> Codec-ID/Info                            : High Efficiency Video Coding with Dolby Vision
> Dauer                                    : 2 h 14 min
> Bitrate                                  : 3 410 kb/s
> Breite                                   : 1 920 Pixel
> Höhe                                     : 1 080 Pixel
> Bildseitenverhältnis                     : 16:9
> Modus der Bildwiederholungsrate          : konstant
> Bildwiederholungsrate                    : 23,976 (24000/1001) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0 (Type 2)
> Bit depth                                : 10 bits
> Bits/(Pixel*Frame)                       : 0.069
> Stream-Größe                             : 3,21 GiB (7%)
> Default                                  : Nein
> Kodierungs-Datum                         : UTC 2019-03-06 12:44:36
> Tagging-Datum                            : UTC 2019-03-06 12:44:36
> Color range                              : Limited
> Color primaries                          : BT.2020
> Transfer characteristics                 : PQ
> Matrix coefficients                      : BT.2020 non-constant
> Mastering display color primaries        : Display P3
> Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
> Codec configuration box                  : hvcC+dvcC

**Comment by martinpickett** [comment]
@CaptSonic It looks like that file is a Dolby Vision file. This is the third major HDR format (the other two being HDR10 and HDR10+). The scripts that have been posted to this thread only work on HDR10 formatted videos.

There has been work done on converting Dolby Vision files, but it is complex, error prone and slow. The best I can do is point you towards another tool written by someone not part of this (`other_video_transcoding`) community. I have not personally used this tool but I have seen other use it successfully.

https://github.com/quietvoid/dovi_tool

My rough understanding is that you have to run this tool on the original file to extract the Dolby Vision metadata (and RPU file) which you can then use as an input when encoding with x265.

**Comment by CaptSonic** [comment]
Hi, thanks for the answer.
It was both in the file. HDR + Dolby Vision. After I removed the second video stream via MKVToolNix, I was able to run the script.

Thanks for your help.

Black.Panther.2018.German.EAC3D.DL.2160p.UHD.BluRay.HDR.Dolby.Vision.HEVC.Remux-NIMA4K
