### ISSUE TITLE
scanning media failed

### ISSUE THREAD

**Issue by weegie** [donmelton/other_video_transcoding#77]
Hi, I am thinking I am missing a step or misunderstanding some instructions. 
Could I get an example of the process of actually ripping a DVD? 
As in what the commando to run it is and where to run it. 

At the moment wherever I run it from, it gives me a "scanning media failed".

My command is E:\>other-transcode D:\DVD\Cats and D:\DVD\Cats>other-transcode Cats2.mkv
So I am trying to run both from the DVD and from an exisiting .mkv

**Comment by uaos** [comment]
Hi,

First off, you will have to copy the file that you want to run
other-transcode against, from the disc to a folder on a drive. There are
numerous programs to do this; MakeMKV is one which many of us use.

Once you’ve done this, you should have a file saved on your computer with a
.mkv extension. You can then run other-transcode on this .mkv file.

This is quite a high-level summary, but if you need more help, or have
trouble with any steps along the way, do let us know! Make sure you check
out the Wiki as well —
https://github.com/donmelton/other_video_transcoding/wiki 😊

**Comment by donmelton** [comment]
@weegie I'm sorry you're having this problem but my `other-transcode` tool doesn't actually rip DVD or Blu-ray discs. And `other-transcode` can't scan files on mounted discs either because those files are usually encrypted. That's why you're getting the "scanning media failed" error.

As @uaos very nicely suggested, MakeMKV is an excellent tool to decrypt and then copy your videos to your hard drive. And once your ripped video is in a single `.mkv` file, my `other-transcode` tool can work on it.

You can download an evaluation version of the MakeMKV app for free here:

https://www.makemkv.com/

I hope this helps.
