### ISSUE TITLE
Adding 2 surround audio tracks with different bitrates?

### ISSUE THREAD

**Issue by TehMaster** [donmelton/other_video_transcoding#82]
Hey @donmelton,

I am working through some TV show Blurays that have commentary tracks that are already in ac3 640. I am encoding the main surround at 448, and would like to include the commentary tracks in surround format at 384. Is this possible in a single pass? I know I can easily add the commentary track as stereo at 224, but I'd like to keep surround if possible.

Is this a case of needing to separate the tracks, do the work, and remerge after to get my desired results?

Thanks as always!

**Comment by donmelton** [comment]
@TehMaster Currently there's no way to specify different surround or stereo bitrates per track with `other-transcode`. That's intentional because I not only want to keep the option syntax simple and understandable but I also want users to approach transcoding without feeling compelled to twiddle things that, really, don't matter. I mean, seriously, just pick an overall bitrate and move on. :)

But, yes, you could certainly separate the tracks and remerge afterwards. Up to you.

**Comment by TehMaster** [comment]
@donmelton Sometimes I come here just for the sass. :) I really figured that is what you would say, and already laughed at myself for why I do this.. I mean really its only roughly MB difference.. Maybe i just need things to do and fiddle with? All i have is time these days... Ha.

Well fine. 640 across the board it is.

**Comment by donmelton** [comment]
@TehMaster I'm here to entertain if nothing else! And choosing 640 Kbps is easy because that's the default. :)
