### ISSUE TITLE
True-HD Audio Tracks (Pass through & FFmpeg/mkvtoolnix output)

### ISSUE THREAD

**Issue by TehMaster** [donmelton/other_video_transcoding#85]
Hi @donmelton (and all),

Is there a way to pass through a True-HD track? I know the option exists for DTS... My current method is converting a 4k video, and then adding the true-hd track back via MKVToolNix (which I originally used to separate the true-HD into a .mka file).

Secondly - Can somehow give me the ffmpeg code to just rip the True-HD tracks? I tried using the below, but there is a filesize difference between it and the one ripped using MKVtoolNix (and mediainfo on the original file). Is ffmpeg not copying header data in this case?
Original/MKvtoolNix rip: 4,677,821 KB
Ffmpeg rip: 4,677,393 KB
ffmpeg -i "mkv" -vn -c:a copy output.mka

Until we find an easy way to encode True-HD tracks down to 8ch EAC-3 i've decided to simply keep the true_HD tracks. This brings the average 4k movie encode to around 16GB, but i guess storage is cheap right? Has anybody creatively solved this problem?

**Comment by donmelton** [comment]
@TehMaster Yes, there's a way to pass through any audio track in its original format. For the main track, add this to your command line:

```
--main-audio 1=original
```

For additional tracks (in this example, all those in the English), add this:

```
--add-audio eng=original
```

That's the correct `ffmpeg` command for copying the audio track. I suspect the size difference is just padding or metadata. I wouldn't worry about it.

Keep in mind that retaining the original TrueHD track is tremendously wasteful of space. In some cases, the audio can be over half the size of the transcoded video track. Trust me, you're much better off just transcoding it to DD+ format even if you're losing two channels. My two cents.

**Comment by TehMaster** [comment]
Thansk @donmelton! Of course it was something as simple as adding '=original'; i had assumed i was missing something. Also good to know about the ffmpeg size difference as I dont have the confidence (aka knowledge) to make those calls.

I absolutely agree about True-HD being a HUGE space suck and waste, but i can absolutely tell the difference between a 6ch EAC3 vs the true-HD tracks, and that is not just because of the extra channels. There is added clarity/details, soundstage, and i highly feel the surround movement flows better. The sound is more immersive instead of simply moving from speaker to speaker. This weekend i watched my 4k encoded version of John wick flipping between the true-hd (copied) and eac3 (encoded) audio tracks, and the difference was immediately noticeable. I then set my receiver to just 5.1 mode and repeated the tests, and again experienced the same thing - noticeable difference.

I would LOVE a better solution than keeping True-HD tracks, and know they exist; I have seen 8ch eac3 tracks (6ch core, 2 ch additional, 1,024 kb/s) floating around, but it seems you need professional dolby software for this and no free solutions exist. This would be my ideal solution. I read an article about using EAC3to to convert audio to 8ch wavs, then compiling using adobe audition to create an 8ch eac3, but i could not figure this out.

**Comment by wintervaler** [comment]
A few weeks ago I went down a deep, deep rabbit hole on this (mostly for fun), @TehMaster, as it seems you have too! 😄 Unfortunately, all that I have gleaned is that at the moment it is very impossible to encode a 7.1-channel EAC3 file with any free encoder 😢. The officially certified Dolby Digital Plus [encoders](https://professional.dolby.com/broadcast/partner-products/) that you can purchase on the software front are increasingly scarce as well - I recall reading that even the built-in support for "certified" DD and DD+ encoders in Adobe CC, which it sounds like you have already read about, dropped off in 2018 and you can only add support back in with an SDK from something like [MainConcept](https://www.mainconcept.com/us/products/for-developers/audio/dolby-digital-plus.html). I think SurCode also makes a DD+ encoder that supports 7.1 channels, and there may be several others. But a lot of these are done at a very high-level professional level with hardware encoders for broadcast or over-the-top streaming, I think. Even Apple's Compressor, which is certified DD+, doesn't have 7.1 channel capabilities.

You _could_ use the Dolby Media Producer Suite from Dolby itself (if you can find a licensed retailer that will sell it to you for a cool several thousand dollars 😲), but it appears to be really outdated from a compatibility perspective - while it performs the functions you need, it's Mac-only -- and only 32-bit Mac, I think, so you'd need a) a Mac and b) a Mac that is running something pre-macOS 10.14 Mojave.

Depending on your client, some other options I read about were encoding 7.1 OPUS or 7.1 AAC, if your client apps/hardware support it -- a rarity, though. And OPUS may not save you space, though I don't know for sure. 

If you want, you can use `ffmpeg` to output 8-channel wavs from a TrueHD track, if you want, rather than `eac3to`, which I find to be a pain in the ass (especially if you're not on Windows). This is the command I have used to try this for `ffmpeg` -- you can feed it a video track and it will automatically select the first/highest-quality audio track:

```
ffmpeg -I 'input.mkv' -filter_complex "channelsplit=channel_layout=7.1[FL][FR][FC][LFE][BL][BR][SL][SR]" \
-c:a pcm_s24le -map "[FL]" front_left.wav \
-c:a pcm_s24le -map "[FR]" front_right.wav \
-c:a pcm_s24le -map "[FC]" front_center.wav \
-c:a pcm_s24le -map "[LFE]" lfe.wav \
-c:a pcm_s24le -map "[BL]" back_left.wav \
-c:a pcm_s24le -map "[BR]" back_right.wav \
-c:a pcm_s24le -map "[SL]" side_left.wav \
-c:a pcm_s24le -map "[SR]" side_right.wav
```

You'll want to make sure your codec for each channel is right - if you have a 16-bit source file vs. 24-bit, I think your codec would be `pcm_s16le`, or you may actually be able to leave out the codec flags in that case. You'd also want to check the "layout" of the original audio track in your input MKV in the `ffmpeg -i` output (the scan of the file should read something like `Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit) (default)` in the info for the stream you want to extract. You can get a full list of those by running `ffmpeg -layouts`. There's also more info on this here: https://trac.ffmpeg.org/wiki/AudioChannelManipulation.

In theory, at least, you can then use those wavs with a professional encoder to put everything back together into a multichannel track, though of course without access to one of those it doesn't make much sense to extract the individual wavs in the first place. 

Sorry for the incredible word vomit here but I hope at least it is validating that there is nothing presently to be done about the lack of 7.1-channel encoding with EAC3. Doesn't mean there won't be one day (probably by the time the next great codec is out), and I plan to keep an eye on it and update this issue thread if there's anything useful to add!

**Comment by donmelton** [comment]
@wintervaler Thanks for this very detailed writeup!

**Comment by TehMaster** [comment]
@wintervaler Seriously appreciate the post. It would appear you and I took a very similar (and depressing) journey down this road and came to the same conclusion. I have everything i need to continue this outside of the Dolby Media Producer Suite (IT guy here, so plenty of extra and old hardware), but I am just not confident i will get the results I want.

I also find eac3to a PITA. I as well will continue to check into this from time to time and will update if I find anything useful. 

@donmelton Is there a discord this community is on, and if so may I join?

**Comment by donmelton** [comment]
@TehMaster We have a Slack channel that I can happily invite you to join! I just need your email address to do that. If you don't want to post that here, just send me an email. My email address is explained here:

https://donmelton.com/contact/

**Comment by TehMaster** [comment]
Right on! Appreciate that @donmelton. TehMasterCain on gmail.

**Comment by heelphan** [comment]
Hey - I am loving this topic!  I would also love an invite to the Slack channel.  george.carson at gmail.  Thanks!

**Comment by donmelton** [comment]
@TehMaster Invitation incoming, sir! I may be AFK when you show up. We mostly hang out in #general.

**Comment by donmelton** [comment]
@heelphan You opened that nice DTS-HD issue back in August, right? If so, that was a good question. Are you up for testing new releases of `other-transcode` and contributing in other support ways?

**Comment by heelphan** [comment]
> @heelphan You opened that nice DTS-HD issue back in August, right? If so, that was a good question. Are you up for testing new releases of `other-transcode` and contributing in other support ways?

Yep, that was me!  Sure, I would be up for testing and also contributing any support I can offer.  Thanks!

**Comment by donmelton** [comment]
@heelphan Okie dokie! I just sent you an email to the address you gave me. Welcome!

**Comment by catdroid75** [comment]
I'm trying to keep the TrueHD tracks, but keep getting this error.

> Too many packets buffered for output stream 0:1.

My input:

>c:\Melton>other-transcode --hevc --nvenc-temporal-aq --crop 3840:1600:0:280 --main-audio 1=original "I:\4K Remux\3840-1600-0-280\Deadpool (2016).mkv"

Any help I can get I would greatly appreciate. Thanks!

Detail:

> c:\Melton>other-transcode --hevc --nvenc-temporal-aq --crop 3840:1600:0:280 --main-audio 1=original "I:\4K Remux\3840-1600-0-280\Deadpool (2016).mkv"
> Verifying "ffprobe" availability...
> Verifying "ffmpeg" availability...
> Verifying "mkvpropedit" availability...
> Finding encoders...
> Scanning media...
> duration = 01:48:06.24
> Stream mapping:
>  0 = hevc_nvenc / 12000 Kbps
>  1 = copy
> Command line:
> ffmpeg -loglevel error -stats -i "I:\4K Remux\3840-1600-0-280\Deadpool (2016).mkv" -map 0:0 -filter:v yadif=deint=interlaced,crop=3840:1600:0:280 -c:v hevc_nvenc -pix_fmt:v p010le -b:v 12000k -maxrate:v 36000k -rc:v vbr_hq -spatial_aq:v 1 -temporal_aq:v 1 -color_primaries:v bt2020 -color_trc:v smpte2084 -colorspace:v bt2020nc -metadata:s:v title= -disposition:v default -map 0:1 -c:a:0 copy -metadata:s:a:0 title= -disposition:a:0 default -sn -metadata:g title= "Deadpool (2016).mkv"
> Transcoding...
> Too many packets buffered for output stream 0:1.
> C:/Ruby26-x64/bin/other-transcode: transcoding failed: Deadpool (2016).mkv

Output from MediaInfo:

> General
> Unique ID                                : 226280182694000317147211450985786412132 (0xAA3BFA5C0E9A31C2484F197159C08C64)
> Complete name                            : I:\4K Remux\3840-1600-0-280\Deadpool (2016).mkv
> Format                                   : Matroska
> Format version                           : Version 4
> File size                                : 38.3 GiB
> Duration                                 : 1 h 48 min
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 50.7 Mb/s
> Encoded date                             : UTC 2020-12-04 14:07:32
> Writing application                      : mkvmerge v51.0.0 ('I Wish') 64-bit
> Writing library                          : libebml v1.4.0 + libmatroska v1.6.2
> 
> Video
> ID                                       : 1
> Format                                   : HEVC
> Format/Info                              : High Efficiency Video Coding
> Format profile                           : Main 10@L5.1@High
> HDR format                               : SMPTE ST 2086, HDR10 compatible
> Codec ID                                 : V_MPEGH/ISO/HEVC
> Duration                                 : 1 h 48 min
> Bit rate                                 : 45.0 Mb/s
> Width                                    : 3 840 pixels
> Height                                   : 2 160 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 (24000/1001) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0 (Type 2)
> Bit depth                                : 10 bits
> Bits/(Pixel*Frame)                       : 0.226
> Stream size                              : 34.0 GiB (89%)
> Writing library                          : ATEME Titan KFE 3.7.3 (4.7.3.1003)
> Default                                  : Yes
> Forced                                   : No
> Color range                              : Limited
> Color primaries                          : BT.2020
> Transfer characteristics                 : PQ
> Matrix coefficients                      : BT.2020 non-constant
> Mastering display color primaries        : Display P3
> Mastering display luminance              : min: 0.0000 cd/m2, max: 1000 cd/m2
> 
> Audio #1
> ID                                       : 2
> Format                                   : MLP FBA 16-ch
> Format/Info                              : Meridian Lossless Packing FBA with 16-channel presentation
> Commercial name                          : Dolby TrueHD with Dolby Atmos
> Codec ID                                 : A_TRUEHD
> Duration                                 : 1 h 48 min
> Bit rate mode                            : Variable
> Bit rate                                 : 5 024 kb/s
> Maximum bit rate                         : 8 466 kb/s
> Channel(s)                               : 8 channels
> Channel layout                           : L R C LFE Ls Rs Lb Rb
> Sampling rate                            : 48.0 kHz
> Frame rate                               : 1 200.000 FPS (40 SPF)
> Compression mode                         : Lossless
> Stream size                              : 3.79 GiB (10%)
> Title                                    : TrueHD Atmos 7.1
> Language                                 : English
> Default                                  : Yes
> Forced                                   : No
> Number of dynamic objects                : 13
> Bed channel count                        : 1 channel
> Bed channel configuration                : LFE

**Comment by donmelton** [comment]
@catdroid75 I'm sorry you're having this problem. This sometimes happens when including tracks in their original format. Try adding `--max-muxing-queue-size 1024` to your command line to see if that helps.

**Comment by catdroid75** [comment]
Looking good so far. Thanks, @donmelton !
