### ISSUE TITLE
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scaler_0'

### ISSUE THREAD

**Issue by cassidyjames** [donmelton/other_video_transcoding#96]
I'm not sure what the root cause is here, but for a handful of movies, I'm getting this error:

```
$ other-transcode --crop auto ../MakeMKV/V\ For\ Vendetta/V\ For\ Vendetta\ \(2006\).mkv 
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Trying "h264_nvenc" video encoder...
Trying "h264_vaapi" video encoder...
Getting muxer capabilities...
Scanning media...
Detecting crop...
...
...
crop = 1920:812:0:134
duration = 02:12:32.384
Stream mapping:
 0 = h264_vaapi / 6000 Kbps
 1 = copy
Command line:
ffmpeg -loglevel error -stats -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i ../MakeMKV/V\ For\ Vendetta/V\ For\ Vendetta\ \(2006\).mkv -map 0:0 -filter:v crop\=1920:812:0:134 -c:v h264_vaapi -b:v 6000k -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -metadata:s:v title\= -disposition:v default -map 0:1 -c:a:0 copy -metadata:s:a:0 title\= -disposition:a:0 default -sn -metadata:g title\= V\ For\ Vendetta\ \(2006\).mkv
Transcoding...
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
/home/cassidyjames/.gems/bin/other-transcode: transcoding failed: V For Vendetta (2006).mkv
```

I've converted a dozen or so other movies just fine, but some are giving me this.

### System Info

Intel Core i7-5557U CPU
16 GB RAM
elementary OS 5.1 (Ubuntu 18.04 LTS)

**Comment by cassidyjames** [comment]
Log file:

[_ffmpeg_16266_32271.mkv.log](https://github.com/donmelton/other_video_transcoding/files/5936282/_ffmpeg_16266_32271.mkv.log)

**Comment by donmelton** [comment]
@cassidyjames Just out of curiosity, are the other failures with inputs containing video in VC-1 format?

You can determine the format using `other-transcode --scan /path/to/input.mkv`.

**Comment by donmelton** [comment]
@cassidyjames Thanks for the `.log` file! Looking at it now...

**Comment by cassidyjames** [comment]
@donmelton yes, both include `format = vc1` in that output.

**Comment by donmelton** [comment]
@cassidyjames Aha! OK, now we have to figure out why VAAPI is barfing on that. I'll consult the HiveMind™ but I might not get an answer until tomorrow.

**Comment by cassidyjames** [comment]
@donmelton no worries! Thanks so much for your quick response on this. I'll continue ripping my other movies. :)

**Comment by donmelton** [comment]
@cassidyjames No problem. This is what I do for fun. :)

Do me a favor and try again but add `--decode none` to your command line and see if that works. That should disable hardware accelerated decoding which might be causing the problem.

**Comment by cassidyjames** [comment]
@donmelton that has started successfully! Thanks!

**Comment by donmelton** [comment]
@cassidyjames Woo hoo! OK, that seems to be a safe workaround. Still, VAAPI shouldn't barf on VC-1 so we need to figure that out. I'll leave this open until we do.

**Comment by ttyS0** [comment]
@cassidyjames 

That's a rather old version of `FFmpeg`, and it's possible that's what's causing the trouble. I also have a rip of `V For Vendetta`, and I was able to run a VAAPI encode. In my case I don't use a distribution packaged `FFmpeg`, but rather one built into a docker container. 

I created a directory structure to try and mimic yours:

```
/home/sean/MakeMKV/V For Vendetta/
/home/sean/out/
```

I put the rip into the `/home/sean/MakeMKV/V For Vendetta/` directory. Then, from the `/home/sean/out` directory, I ran the following:

`docker run --rm --device /dev/dri:/dev/dri -v /home/sean/MakeMKV:/src -v $(pwd):$(pwd) -w $(pwd) hub.skj.dev/img/other-transcode:qsv-0.7.0 --crop auto --vaapi "/src/V For Vendetta/V For Vendetta.mkv"`

In case you're unfamiliar with Docker, the `-v /home/sean/MakeMKV:/src` part maps the `/home/sean/MakeMKV` directory from the host to the `/src` directory within the container. The `-v $(pwd):$(pwd) -w $(pwd)` maps the current directory, and sets it as the working directory. This means that when referring to the location of the source `/src/V For Vendetta/V For Vendetta.mkv` is used, and the output is put into the directory you are in when `docker run...` is executed. 

This is what I got:

```
sean@gandalf:~/out$ docker run --rm --device /dev/dri:/dev/dri -v /home/sean/MakeMKV:/src -v $(pwd):$(pwd) -w $(pwd) hub.skj.dev/img/other-transcode:qsv-0.7.0 --crop auto --vaapi "/src/V For Vendetta/V For Vendetta.mkv"
Verifying "ffprobe" availability...
Verifying "ffmpeg" availability...
Verifying "mkvpropedit" availability...
Finding encoders...
Getting muxer capabilities...
Scanning media...
Detecting crop...
...
crop = 1920:812:0:134
duration = 02:12:32.384
Stream mapping:
 0 = h264_vaapi / 6000 Kbps
 1 = copy
Command line:
ffmpeg -loglevel error -stats -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i /src/V\ For\ Vendetta/V\ For\ Vendetta.mkv -map 0:0 -filter:v crop\=1920:812:0:134 -c:v h264_vaapi -b:v 6000k -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -metadata:s:v title\= -disposition:v default -map 0:1 -c:a:0 copy -metadata:s:a:0 title\= -disposition:a:0 default -sn -metadata:g title\= -default_mode passthrough V\ For\ Vendetta.mkv
Transcoding...
frame=62363 fps=153 q=-0.0 size= 2018560kB time=00:43:21.02 bitrate=6357.5kbits/s speed=6.39x
```

I'm running this on an 8th Gen NUC with an i5-8259U and Iris Plus 655 GPU, so it's going to run a bit faster than your Broadwell, but other than that I would expect it to work the same. 

If you already have Docker installed, you might want to try using the Docker image. The `hub.skj.dev/img/other-transcode:qsv-0.7.0` pulls from my home Docker registry, but I also push to Docker Hub, so you can use `ttys0/other-transcode:qsv-0.7.0` as well. Otherwise, I'd suggest getting a newer version of `FFmpeg`. The version I have built into the image right now is `4.3.1`. 

Hope that helps, and feel free to give me a yell if any or all of that is totally confusing. 😎 

I've also included the log file for that encode, since I'm still working on my first cup of coffee and it took me that long to fix all the typos in this reply. 

[V For Vendetta.mkv.log](https://github.com/donmelton/other_video_transcoding/files/5937015/V.For.Vendetta.mkv.log)

**Comment by donmelton** [comment]
@ttyS0 Thanks for the testing and the detailed comment! And, of course, all those Docker containers. 😄

**Comment by cassidyjames** [comment]
@ttyS0 thank you! I may give Docker a look, and/or I might finally bite the bullet and upgrade my NUC to a 20.04 base, which I presume should offer at least a new_er_ ffmpeg. I have been running stable elementary OS on this machine from before it was a media PC, but it’s mostly headless these days anyway. 😅 Thanks again!

**Comment by donmelton** [comment]
@cassidyjames OK, I'm going to close this because it's essentially resolved now. But feel free to comment here again or open new issues.
